version: '3.9'

services:
  database:
    image: mysql
    container_name: corelab_notes
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'corelab_notes'
    ports:
      - '3306:3306'
